### ISSUE TITLE
Rewording p. 126

### ISSUE THREAD

**Issue by annnagatsuki** [vEnhance/egmo-book-errata#6]
> It is important that x + y + z = 1 when doing calculations with displacement vectors. (p. 126)

Easily achievable alternatives:

1. change "x + y + z = 1" to "x + y + z = 0".
2. delete "however" in the preceding sentence.

Things to be considered:

- The word ‘however’ in “… since x + y + z = 1. As a result, however: It is important that x + y + z = 1 when doing calculations with displacement vectors” implies that two topics are somewhat adversative (opposite). Since the former topic is the coordinates of points, the latter topic should be the displacement vectors, and its focus should also be the important fact: x + y + z = 1, which is the same as the former one!
- Right after this sentence in the same page, x + y + z = 0 is called as the sum of the coordinates in a displacement vector. So is the proof of Theorem 7.16, and Theorem 7.15 and 7.24 where x + y + z = 1 is emphasized are only for points, not for displacement vectors.
- Motivation for using pseudo-displacement vector is explained as “we only need one of the displacement vectors to be zero for the entire product to be zero,” which implies that the convenience of pseudo-ones is substantiated by saying x + y + z = 0 is important in displacement vectors.

**Comment by vEnhance** [comment]
In 3864541 I made the following even more explicit version:

```
commit 3864541c1e82112134bcf160ed03a609b724ab8f
Author: Evan Chen <evan@evanchen.cc>
Date:   Tue Jan 3 05:41:29 2023 -0500

    Elaborate even more

diff --git a/main.tex b/main.tex
index bed064d..15039c3 100644
--- a/main.tex
+++ b/main.tex
@@ -142,8 +142,9 @@ I currently do not have any plans to create a second edition.
     It is important that $x+y+z=1$ when doing calculations with displacement vectors.
   \end{quote}
   is confusing as written, since in a displacement vector the coordinates sum to zero.
-  It would be better to say,
-  ``coordinates of points should be normalized to sum $1$''.
+  It would be better to say something like
+  ``Coordinates of points should be normalized to sum $1$,
+  so that displacement vectors always have coordinates with sum $0$''.
 \item[p.\  126] in Theorem 7.14 and proof, $|PQ|^2$ should technically be just $PQ^2$.
 \item[p.\  130] in the proof of Example 7.20, change $(bs:b:2b)=(bs:b:c)$ to $(bt:b:2b)=(bt:b:c)$.
   Omit $s=t/b$ which is never used.
```

I hope that's clear now!
