### ISSUE TITLE
Extra todo's from #4

### ISSUE THREAD

**Issue by vEnhance** [vEnhance/egmo-book-errata#9]
Creating a separate issue so I can track these. From @annnagatsuki 

> Additional ToDos:
> 
> Reword p. 126: “It is important that x + y + z = 1 when doing calculations with displacement vectors” should be “… x + y + z = 0 ….”
> Solution to Example 7.30: an abuse of notation in defining the coordinates of point P.
> There is a definition of two circles being orthogonal but no definition of a circle being orthogonal to another circle.
> There is no definition of the complete quadrilateral being cyclic such as the one in tr011ey.
> p. 274: ``isogonal with respect to \angle{BAC}'' is undefined in this book.
> Solution 11.11: ``the angle bisector''.
> Solution 10.30: This logic of the first sentence seems very strange to me. The analogous calculation does not imply the second expression and the second one itself will not give the third one. Even if the subject of the relative clause should be interpreted as “the analogous calculation,” which would make some sense to me, the former issue still does not resolve at all. Above all, this introduction might imply that “directed SAS” is going to be used to show the similarity, even though we are going to show accordingly with the definition itself by using cyclic permutations of indices.

**Comment by annnagatsuki** [comment]
(With the exception of the first item, I have already proposed corrections, which you are free to delete or alter as you wish.)

**Comment by vEnhance** [comment]
I think these should all be resolved now, please re-open if not.
